# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppusersUserprofile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('picture', models.CharField(blank=True, max_length=90, null=True)),
                ('gender', models.CharField(blank=True, max_length=90, null=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=90, null=True)),
                ('address', models.CharField(blank=True, max_length=90, null=True)),
                ('availablecredit', models.FloatField(blank=True, null=True)),
                ('gainobtained', models.FloatField(blank=True, null=True)),
                ('classcustomer', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appusers_userprofile',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
