# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appusers', '0002_auto_20161108_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('picture', models.CharField(blank=True, max_length=90, null=True)),
                ('gender', models.CharField(blank=True, max_length=90, null=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=90, null=True)),
                ('address', models.CharField(blank=True, max_length=90, null=True)),
                ('availablecredit', models.FloatField(blank=True, null=True)),
                ('gainobtained', models.FloatField(blank=True, null=True)),
                ('classcustomer', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
