# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0006_auto_20161109_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
