# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0008_auto_20161109_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mierda',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('mierdados', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
