# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('appusers', '0009_mierda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCustomer',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=90, null=True)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=90, null=True)),
                ('picture', models.CharField(blank=True, max_length=90, null=True)),
                ('gender', models.CharField(blank=True, max_length=90, null=True)),
                ('availablecredit', models.FloatField(blank=True, null=True)),
                ('gainobtained', models.FloatField(blank=True, null=True)),
                ('classcustomer', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mierda',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
