# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('appusers', '0010_auto_20161109_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=90, null=True)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=90, null=True)),
                ('gender', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilecustomer',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileCustomer',
        ),
    ]
