# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0011_auto_20161109_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
