# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0012_auto_20161110_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPerfil',
        ),
    ]
