# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('appusers', '0013_delete_usuarioperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('available_credit', models.FloatField(blank=True, null=True)),
                ('gain_obtained', models.FloatField(blank=True, null=True)),
                ('class_customer', models.CharField(blank=True, max_length=4, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('picture', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
    ]
