# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0014_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='USER_PROFILE',
        ),
    ]
