# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0015_auto_20161110_1745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
